# This is a basic workflow to help you get started with Actions

name: Create and rename branch for issues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  issues:
    types: [assigned]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        with: 
          branch: 'potato'
