# This is a basic workflow to help you get started with Actions

name: Create and rename branch for issues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  issues:
    types: [assigned, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-branch:
    runs-on: ubuntu-latest
    name: Creating Branch
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        if: (github.event.issues == 'assigned')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          branch: ${{ github.event.issue.title }}
  edit-branch:
    runs-on: ubuntu-latest
    name: Renaming Branch
    steps:
      - if: (github.event.issues == 'edited')
      - run: |
          git branch -m new_branch
          git push origin -u new_branch
          git push origin --delete test
       
